#!/usr/bin/env bash
# This fetches all subdomain information
# of domain passed in

domain=$1
subdomain=$2
 
declare -a list_subdomains=("www" "lb-01" "web-01" "web-02")
 
parseinfo () {
    parseresult=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4  " " $5}')
    echo "$2 $parseresult" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
} 

if [ $# -eq 1 ]; then
    for i in ${list_subdomains[@]}
    do
        parseinfo $1 $i
    done
elif [ $# -eq 2 ]; then
    parseinfo $1 $2
fi
