#!/usr/bin/env bash
# this installs nginx
# and configures it for redirection

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https//:google.com permanent;' /etc/nginx/sites-enabled/default
sudo service nginx start
