#!/usr/bin/env bash
# this installs nginx
# and configures a redirection

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" > /var/www/html/index.html
service nginx start
