#!/usr/bin/env bash
# this configurs ubuntu server t requirement and also
#adds custom header

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
mkdir -p var/www/html
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://google.com permanent;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a error_page 404 error404.html;' /etc/nginx/sites-available/default
sed -i 'server_name _;/a add_header X-Served-by $HOSTNAME;'
sudo service nginx reload
sudo service nginx start
