#!/usr/bin/env bash
# Displays Best School and hi on
# the 9th iteration

var=0
lim=8
while [ "$var" -lt 10 ];
do
    if [ "$var" == "$lim" ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    let var=var+1
done
