#!/usr/bin/env bash
# displays badluck on fourth iteration
# displays goodluck on 8th iteration

var=0
fourth=3
eighth=7
while [ "$var" -lt 10 ];
do
    if [ "$fourth" == "$var" ]
    then
        echo "bad luck"
    elif [ "$eighth" == "$var" ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let var=var+1
done
