#!/usr/bin/env bash
# uses switch statement to display
# different messages on case 4, 9 and 17

var=1

while [ "$var" -le 20 ];
do
    echo "$var"
    case "$var" in
    4)
        echo "bad luck from China";;
    9)
        echo "bad luck from Japan";;
    17)
        echo "bad luck from Italy";;
    esac 
    let var=var+1
done
