#!/usr/bin/env bash
# prints the time for 12hours and 59 minutes

hr=1
while [ "$hr" -le 12 ]; 
do
    echo "Hour: $hr"
    min=1
    while [ "$min" -lt 60 ]; 
    do
	    echo "$min"
	    ((min++));
    done
    ((hr++));
done
