#!/usr/bin/env bash
# displays messages on conditions
# if file exist or not
# if file is empty or not
# if file is a regular file or not

FILE="school"
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
    if [ -s "$FILE" ]; then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f "$FILE" ]; then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
