#!/usr/bin/env bash
# this configures nginx to run as 
# the nginx user

sudo chown nginx:nginx /etc/nginx/nginx.conf
chmod uga+rwx /etc/nginx/nginx.conf
sed -i "/user www-data;/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
