#!/usr/bin/env bash
# this configures nginx to run as 
# the nginx user

chmod 644 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/#user www-data;/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
su -s /bin/bash -c service nginx start nginx
